// The YC product-demo recording frame (1920×1080, dark theme). Opens with a
// rich 27-second intro — floating code snippets, a wordmark reveal, a parallax
// persona strip and the positioning line — then crossfades into the live
// product tour. The recorder drives narration from here so each line lands on
// the exact animation beat it was written for.
import type { CSSProperties } from "react";
import { useEffect, useRef, useState } from "react";
import { WrapboxLogo, WrapboxWordmark } from "../ui/logo";
import { photoOf } from "../ui/logos";
import type { TourCase } from "../tour/types";

const VIEW_W = 1920, VIEW_H = 1080;
const APP_W = 1600, APP_H = 900;
const SCALE = VIEW_W / APP_W;

// Narration points for the opening scene; the recorder plays each clip at the
// listed millisecond so the voice always matches the animation. Files are
// generated by docs/_voice.ts into docs/voice-v2/yc-intro/.
export const INTRO_NARR = [
  { i: 0, at: 1000,  file: "yc-intro/0-ai-agents.mp3", say: "AI agents are already running your code, reading your secrets, calling your databases. Wrapbox decides what each one is allowed to do." },
  { i: 1, at: 9400,  file: "yc-intro/1-personas.mp3",  say: "Priya writes the rules. Daniel runs the agents. Alex approves the risky calls. Maya holds the override." },
  { i: 2, at: 19400, file: "yc-intro/2-not-edr.mp3",   say: "Not E-D-R. Not M-D-M. The first runtime authorization engine for every AI agent." },
];
export const INTRO_TOTAL_MS = 27_200;

const CODE_SNIPPETS = [
  { lang: "shell", text: "$ cat /etc/.env",                                      tone: "block",     x: 110,  y: 180, delay: 200,  rot: -3 },
  { lang: "sql",   text: "DROP TABLE customers;",                                tone: "block",     x: 1460, y: 240, delay: 450,  rot: 2 },
  { lang: "shell", text: "$ git push --force origin main",                       tone: "review",    x: 190,  y: 730, delay: 700,  rot: 1 },
  { lang: "http",  text: "POST api.openai.com/v1/chat/completions",              tone: "constrain", x: 1420, y: 760, delay: 950,  rot: -2 },
  { lang: "shell", text: "$ aws iam attach-role-policy AdministratorAccess",     tone: "block",     x: 70,   y: 460, delay: 1150, rot: -1 },
  { lang: "http",  text: "POST hooks.slack.com/services/T0…",                    tone: "allow",     x: 1500, y: 500, delay: 1350, rot: 3 },
];

const PERSONAS = [
  { userId: "u-priya",  name: "Priya Menon",  role: "Admin",               job: "writes the rules" },
  { userId: "u-daniel", name: "Daniel Kim",   role: "Developer",           job: "runs the agents" },
  { userId: "u-alex",   name: "Alex Morgan",  role: "Engineering Manager", job: "approves risky calls" },
  { userId: "u-maya",   name: "Maya Chen",    role: "Security",            job: "holds the override" },
];

interface TourMsg { type: "wrapbox-tour"; id: string; step: number; status: string; narrated?: number; at?: number }
type Rec = (ev: Record<string, unknown>) => void;

export function RecordYc({ tc }: { tc: TourCase }) {
  const frame = useRef<HTMLIFrameElement>(null);
  const [phase, setPhase] = useState<"idle" | "intro" | "tour">("idle");
  const [step, setStep] = useState(0);
  const [status, setStatus] = useState("loading");
  const total = tc.steps.length;

  // The recorder calls window.__wbGo() once capture is running, so the whole
  // intro and the first narration frame are inside the file.
  useEffect(() => { (window as unknown as { __wbGo: () => void }).__wbGo = () => setPhase("intro"); }, []);

  // Drive the intro: the three narration lines fire at their fixed moments so
  // the recorder lays each clip on the exact animation beat, and the tour
  // iframe mounts after the intro's total length.
  useEffect(() => {
    if (phase !== "intro") return;
    const rec = (window as unknown as { __wbRec?: Rec }).__wbRec;
    const timers: number[] = [];
    for (const n of INTRO_NARR) {
      timers.push(window.setTimeout(() => rec?.({ narrated: n.i, at: Date.now(), intro: true, file: n.file }), n.at));
    }
    timers.push(window.setTimeout(() => setPhase("tour"), INTRO_TOTAL_MS));
    return () => { timers.forEach((t) => window.clearTimeout(t)); };
  }, [phase]);

  useEffect(() => {
    const rec = (window as unknown as { __wbRec?: Rec }).__wbRec;
    const on = (e: MessageEvent) => {
      const d = e.data as TourMsg | null;
      if (!d || d.type !== "wrapbox-tour" || d.id !== tc.id || e.source !== frame.current?.contentWindow) return;
      // Tour's narrated events are shifted so they don't collide with intro indices.
      if (typeof d.narrated === "number") rec?.({ narrated: d.narrated + INTRO_NARR.length, at: d.at });
      setStep(d.step); setStatus(d.status);
      if (d.status === "done") rec?.({ done: Date.now() });
      if (d.status === "error") rec?.({ error: d.step });
    };
    window.addEventListener("message", on);
    return () => window.removeEventListener("message", on);
  }, [tc.id]);

  const done = status === "done";
  const pct = done ? 100 : (step / Math.max(1, total - 1)) * 100;

  return (
    <div className="rvy">
      <div className="rvy-view" style={{ width: VIEW_W, height: VIEW_H }}>
        {/* ── Opening scene ── */}
        {phase !== "idle" && (
          <div className={`rvy-intro ${phase === "tour" ? "rvy-intro-out" : ""}`} aria-hidden="true">
            {/* Code snippets drift in, settle, then fade back as the hero arrives. */}
            <div className="rvy-codes">
              {CODE_SNIPPETS.map((c, k) => (
                <div
                  key={k}
                  className={`rvy-code rvy-code-${c.tone}`}
                  style={{ left: c.x, top: c.y, animationDelay: `${c.delay}ms`, ["--rot" as string]: `${c.rot}deg` } as CSSProperties}
                >
                  <div className="rvy-code-bar"><i /><i /><i /><span>{c.lang}</span></div>
                  <div className="rvy-code-body">{c.text}</div>
                </div>
              ))}
            </div>

            {/* Hero: eyebrow + wordmark + headline + sub. */}
            <div className="rvy-hero">
              <div className="rvy-eyebrow">THE AGENTIC SECURITY RUNTIME</div>
              <div className="rvy-logo"><WrapboxLogo size={132} tone="dark" /></div>
              <h1 className="rvy-headline">
                Wrapbox decides<br />what every AI agent is allowed to do.
              </h1>
              <p className="rvy-sub">Not EDR. Not MDM. The first runtime authorization engine for AI agents.</p>
            </div>

            {/* Four personas, each sliding in with a staggered parallax. */}
            <div className="rvy-personas-row">
              {PERSONAS.map((p, k) => {
                const src = photoOf(p.userId);
                return (
                  <div key={p.userId} className="rvy-persona" style={{ animationDelay: `${9700 + k * 220}ms` }}>
                    {src ? <img className="rvy-face" src={src} alt="" /> : <span className="rvy-face rvy-face-mono">{p.name.split(" ").map((w) => w[0]).join("")}</span>}
                    <div className="rvy-persona-name">{p.name}</div>
                    <div className="rvy-persona-role">{p.role}</div>
                    <div className="rvy-persona-job">{p.job}</div>
                  </div>
                );
              })}
            </div>

            {/* Positioning line that lands with the third narration. */}
            <div className="rvy-category">
              <span className="rvy-cat-k">Not EDR.</span>
              <span className="rvy-cat-k">Not MDM.</span>
              <span className="rvy-cat-v">Agentic security runtime.</span>
            </div>

            {/* Platforms Wrapbox governs. */}
            <div className="rvy-platforms">
              <span>Anthropic</span><i /><span>OpenAI</span><i /><span>Google</span><i /><span>Microsoft</span><i /><span>MCP tools</span><i /><span>your own</span>
            </div>

            <div className="rvy-footmark">A LIVE WALKTHROUGH OF THE REAL PRODUCT</div>
          </div>
        )}

        {/* ── Product tour (mounts after the intro) ── */}
        {phase === "tour" && (
          <iframe
            ref={frame}
            src={`tour-v2.html?case=${tc.id}&voice=0&nocap=1&dark=1&speed=0.72`}
            title={tc.title}
            width={APP_W}
            height={APP_H}
            style={{ transform: `scale(${SCALE})` }}
            tabIndex={-1}
          />
        )}

        {/* A thin top progress line — the only live chrome on top of the product. */}
        <div className="rvy-prog" style={{ opacity: phase === "tour" && !done ? 1 : 0 }}>
          <i style={{ width: `${pct}%` }} />
        </div>
        {/* Wordmark pinned to the bottom-right once the tour begins. */}
        <div className="rvy-mark" style={{ opacity: phase === "tour" ? 1 : 0 }}>
          <WrapboxWordmark tone="dark" height={22} />
        </div>

        {/* Closing card, same frame, fades in at the end. */}
        <div className={`rvy-end ${done ? "rvy-end-in" : ""}`}>
          <div className="rvy-logo"><WrapboxLogo size={128} tone="dark" /></div>
          <h1>Wrapbox.</h1>
          <p>The agentic security runtime. Device, Network, Gateway — one brain, every action on record.</p>
          <div className="rvy-end-sub">WRAPBOX.AI</div>
        </div>
      </div>
    </div>
  );
}
