// The investor product-demo recording frame (1920×1080, dark theme), styled
// like a top-tier polished screen-studio film: the real product runs inside a
// rounded floating card on a slow aurora backdrop, an auto-zoom camera glides
// into whatever the decision engine is doing, act stamps punctuate the story,
// and the close counts the workspace's real numbers up on screen.
//
// Cold open: a terminal types a dangerous agent command and a BLOCK stamp
// slams it — the product's whole promise in four seconds, before the title.
import { useEffect, useRef, useState } from "react";
import { WrapboxLogo, WrapboxWordmark } from "../ui/logo";
import { photoOf } from "../ui/logos";
import type { TourCase } from "../tour/types";

const VIEW_W = 1920, VIEW_H = 1080;
const APP_W = 1600, APP_H = 900;
// The app card: 1640 px wide, centred, rounded — backdrop stays visible around it.
const CARD_W = 1640, CARD_SCALE = CARD_W / APP_W, CARD_H = APP_H * CARD_SCALE;

// Narration beats for the opening scene; the recorder plays each clip at the
// listed millisecond so the voice always matches the animation. Files are
// generated by docs/_voice-film.ts into docs/voice-v2/yc-intro2/.
export const INTRO_NARR = [
  { i: 0, at: 1000,  file: "yc-intro2/0-ai-employees.mp3", say: "Your company already has AI employees. They write code, they query databases — and nobody can see what they're allowed to do. Wrapbox can." },
  { i: 1, at: 9900, file: "yc-intro2/1-personas.mp3",     say: "Priya writes the rules. Daniel runs the agents. Alex approves the risky calls. Maya holds the override." },
  { i: 2, at: 19600, file: "yc-intro2/2-category.mp3",     say: "Not antivirus. Not device management. The runtime that decides what every agent may do — at the moment it acts." },
];
export const INTRO_TOTAL_MS = 28_400;

// Cold-open terminal: three real agent attempts, each answered with a stamp.
const TERM_LINES = [
  { cmd: "claude-code · bash$  git push --force origin main",            verdict: "BLOCK",     tone: "block",     at: 1400 },
  { cmd: "finance-agent · sql$  SELECT * FROM customers; -- 500,000 rows", verdict: "REVIEW",  tone: "review",    at: 4000 },
  { cmd: "support-agent · http$  POST customers.csv → ai.enterprise.example", verdict: "CONSTRAIN", tone: "constrain", at: 6600 },
];

const PERSONAS = [
  { userId: "u-priya",  name: "Priya Menon",  role: "Admin",               job: "writes the rules" },
  { userId: "u-daniel", name: "Daniel Kim",   role: "Developer",           job: "runs the agents" },
  { userId: "u-alex",   name: "Alex Morgan",  role: "Engineering Manager", job: "approves risky calls" },
  { userId: "u-maya",   name: "Maya Chen",    role: "Security",            job: "holds the override" },
];

// Question cards shown as the tour crosses into each story (step index → card).
const ACTS: Record<number, { n: string; title: string }> = {
  0:  { n: "QUESTION 01", title: "Can an agent steal your keys?" },
  3:  { n: "QUESTION 02", title: "Where does customer data go?" },
  6:  { n: "QUESTION 03", title: "Can an agent own a whole job?" },
  9:  { n: "QUESTION 04", title: "The agent nobody hired" },
  11: { n: "QUESTION 05", title: "2 a.m. — production is down" },
};

// Closing stats — the workspace's real derived numbers for this recording.
const END_STATS = [
  { v: 20, label: "decisions recorded" },
  { v: 7,  label: "blocked in flight" },
  { v: 1,  label: "shadow agent found" },
  { v: 100, suffix: "%", label: "on the record" },
];

interface TourMsg { type: "wrapbox-tour"; id: string; step: number; status: string; narrated?: number; at?: number }
type Rec = (ev: Record<string, unknown>) => void;

/** Parallax camera: a constant, gentle 1.05 scale whose origin drifts toward
 *  the walkthrough spotlight. Nothing meaningful is ever cropped (origin is
 *  clamped), the scale never pumps, and the origin is quantized so tiny
 *  spotlight shifts don't restart the glide mid-flight (the "buzzing"). */
function useCamera(frame: React.RefObject<HTMLIFrameElement | null>, cam: React.RefObject<HTMLDivElement | null>, active: boolean) {
  useEffect(() => {
    if (!active) return;
    let last = "";
    if (cam.current) cam.current.style.transform = "scale(1.05)";
    const tick = () => {
      const el = cam.current;
      const doc = frame.current?.contentDocument;
      if (!el || !doc) return;
      const spot = doc.querySelector(".tour-spot") as HTMLElement | null;
      let cx = 50, cy = 50;
      if (spot && spot.offsetWidth) {
        cx = Math.max(34, Math.min(66, ((spot.offsetLeft + spot.offsetWidth / 2) / APP_W) * 100));
        cy = Math.max(34, Math.min(66, ((spot.offsetTop + spot.offsetHeight / 2) / APP_H) * 100));
        cx = Math.round(cx / 8) * 8;
        cy = Math.round(cy / 8) * 8;
      }
      const key = `${cx}|${cy}`;
      if (key === last) return;
      last = key;
      el.style.transformOrigin = `${cx}% ${cy}%`;
    };
    const t = window.setInterval(tick, 700);
    return () => window.clearInterval(t);
  }, [active, frame, cam]);
}

export function RecordYc({ tc }: { tc: TourCase }) {
  const frame = useRef<HTMLIFrameElement>(null);
  const cam = useRef<HTMLDivElement>(null);
  const [phase, setPhase] = useState<"idle" | "intro" | "tour">("idle");
  // Starts at -1 so the very first step (0) still counts as a change and
  // fires QUESTION 01's card.
  const [step, setStep] = useState(-1);
  const [status, setStatus] = useState("loading");
  const [act, setAct] = useState<{ n: string; title: string } | null>(null);
  const total = tc.steps.length;

  // The recorder calls window.__wbGo() once capture is running, so the whole
  // intro and the first narration frame are inside the file.
  useEffect(() => { (window as unknown as { __wbGo: () => void }).__wbGo = () => setPhase("intro"); }, []);

  // Drive the intro: narration beats fire at fixed moments, the tour mounts after.
  useEffect(() => {
    if (phase !== "intro") return;
    const rec = (window as unknown as { __wbRec?: Rec }).__wbRec;
    const timers: number[] = [];
    for (const n of INTRO_NARR) {
      timers.push(window.setTimeout(() => rec?.({ narrated: n.i, at: Date.now(), intro: true, file: n.file }), n.at));
    }
    timers.push(window.setTimeout(() => setPhase("tour"), INTRO_TOTAL_MS));
    return () => { timers.forEach((t) => window.clearTimeout(t)); };
  }, [phase]);

  useEffect(() => {
    const rec = (window as unknown as { __wbRec?: Rec }).__wbRec;
    const on = (e: MessageEvent) => {
      const d = e.data as TourMsg | null;
      if (!d || d.type !== "wrapbox-tour" || d.id !== tc.id || e.source !== frame.current?.contentWindow) return;
      // Tour's narrated events are shifted so they don't collide with intro indices.
      if (typeof d.narrated === "number") rec?.({ narrated: d.narrated + INTRO_NARR.length, at: d.at });
      setStep((prev) => {
        if (d.step !== prev && ACTS[d.step]) {
          setAct(ACTS[d.step]);
          window.setTimeout(() => setAct(null), 1700);
        }
        return d.step;
      });
      setStatus(d.status);
      if (d.status === "done") rec?.({ done: Date.now() });
      if (d.status === "error") rec?.({ error: d.step });
    };
    window.addEventListener("message", on);
    return () => window.removeEventListener("message", on);
  }, [tc.id]);

  useCamera(frame, cam, phase === "tour");

  const done = status === "done";
  const pct = done ? 100 : (Math.max(0, step) / Math.max(1, total - 1)) * 100;

  return (
    <div className="rvy">
      <div className="rvy-view" style={{ width: VIEW_W, height: VIEW_H }}>
        {/* Slow aurora backdrop — alive for the whole film. */}
        <div className="rvy-aurora" aria-hidden="true"><i /><i /><i /></div>

        {/* ── Cold open + title (phase: intro) ── */}
        {phase !== "idle" && (
          <div className={`rvy-intro ${phase === "tour" ? "rvy-intro-out" : ""}`} aria-hidden="true">
            {/* Beat 1 · 0–10.4 s: the terminal, and the stamps that answer it. */}
            <div className="rvy-term">
              <div className="rvy-term-bar"><i /><i /><i /><span>what your agents tried today</span></div>
              <div className="rvy-term-body">
                {TERM_LINES.map((l, k) => (
                  <div key={k} className="rvy-term-row" style={{ animationDelay: `${l.at}ms` }}>
                    <span className="rvy-term-cmd">{l.cmd}</span>
                    <span className={`rvy-verdict rvy-verdict-${l.tone}`} style={{ animationDelay: `${l.at + 950}ms` }}>{l.verdict}</span>
                  </div>
                ))}
                <div className="rvy-term-row rvy-term-tail" style={{ animationDelay: "8400ms" }}>
                  <span className="rvy-term-cmd">wrapbox · one brain decided all three — before they ran</span>
                </div>
              </div>
            </div>

            {/* Beat 2 · 10.4–21.4 s: the four people, one product. */}
            <div className="rvy-personas">
              <div className="rvy-personas-head">One product. Four people.</div>
              <div className="rvy-personas-row">
                {PERSONAS.map((p, k) => {
                  const src = photoOf(p.userId);
                  return (
                    <div key={p.userId} className="rvy-persona" style={{ ["--d" as string]: `${10200 + k * 240}ms` } as React.CSSProperties}>
                      {src ? <img className="rvy-face" src={src} alt="" /> : <span className="rvy-face rvy-face-mono">{p.name.split(" ").map((w) => w[0]).join("")}</span>}
                      <div className="rvy-persona-name">{p.name}</div>
                      <div className="rvy-persona-role">{p.role}</div>
                      <div className="rvy-persona-job">{p.job}</div>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Beat 3 · 21.4–30 s: title + category. */}
            <div className="rvy-title">
              <div className="rvy-logo"><WrapboxLogo size={120} tone="dark" /></div>
              <h1 className="rvy-headline">Your company already<br />has AI employees.</h1>
              <p className="rvy-sub">Wrapbox decides what each one is allowed to do — at the moment it acts.</p>
              <div className="rvy-category">
                <span className="rvy-cat-k">Not EDR.</span>
                <span className="rvy-cat-k">Not MDM.</span>
                <span className="rvy-cat-v">Agentic security runtime.</span>
              </div>
            </div>
          </div>
        )}

        {/* ── The product, in a floating card with an auto-zoom camera ── */}
        {phase === "tour" && (
          <div className={`rvy-card ${done ? "rvy-card-out" : ""}`} style={{ width: CARD_W, height: CARD_H }}>
            <div ref={cam} className="rvy-cam">
              <iframe
                ref={frame}
                src={`tour-v2.html?case=${tc.id}&voice=0&nocap=1&dark=1&speed=0.66`}
                title={tc.title}
                width={APP_W}
                height={APP_H}
                style={{ transform: `scale(${CARD_SCALE})` }}
                tabIndex={-1}
              />
            </div>
          </div>
        )}

        {/* Act stamps between chapters. */}
        <div className={`rvy-act ${act ? "rvy-act-in" : ""}`}>
          {act && (<><div className="rvy-act-n">{act.n}</div><div className="rvy-act-t">{act.title}</div></>)}
        </div>

        {/* AI-narration orb — honest presenter bubble. */}
        <div className="rvy-orb" style={{ opacity: phase === "tour" && !done ? 1 : 0 }}>
          <span className="rvy-orb-wave"><i /><i /><i /><i /><i /></span>
          <span className="rvy-orb-label">Wrapbox · AI narration</span>
        </div>

        {/* Thin top progress line. */}
        <div className="rvy-prog" style={{ opacity: phase === "tour" && !done ? 1 : 0 }}>
          <i style={{ width: `${pct}%` }} />
        </div>
        {/* Wordmark pinned bottom-left during the tour. */}
        <div className="rvy-mark" style={{ opacity: phase === "tour" && !done ? 1 : 0 }}>
          <WrapboxWordmark tone="dark" height={22} />
        </div>

        {/* Closing card: logo, line, real numbers counting up, the URL. */}
        <div className={`rvy-end ${done ? "rvy-end-in" : ""}`}>
          <div className="rvy-logo"><WrapboxLogo size={116} tone="dark" /></div>
          <h1>Wrapbox.</h1>
          <p>Runtime authorization for AI agents. Device, Network, Gateway — one brain, every action on record.</p>
          <div className="rvy-end-stats">
            {END_STATS.map((s, k) => (
              <div key={k} className="rvy-end-stat" style={{ animationDelay: `${600 + k * 180}ms` }}>
                <b>{s.v}{s.suffix ?? ""}</b><span>{s.label}</span>
              </div>
            ))}
          </div>
          <div className="rvy-end-sub">WRAPBOX.IO</div>
        </div>
      </div>
    </div>
  );
}
